sudo: required

services:
  - docker

stages:
  - name: test
    if: type != cron
  - name: create_pr_on_new_version
    if: type = cron
  - name: tag_if_new_version
    if: type = push AND branch = master

jobs:
  include:
    - stage: test
      script: .test/test.sh
    - stage: create_pr_on_new_version
      script: .release/create-pr-on-new-version.sh
    - stage: tag_if_new_version
      script: .release/tag-if-new-version.sh
